name: Playwright Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  schedule:
    - cron: '0 0 * * *'  # 매일 0시 UTC = 한국시간 오전 9시

  workflow_dispatch:  # 수동 실행 설정

jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test
        env:
          STANDARD_USER: ${{ secrets.STANDARD_USER }}
          LOCKED_OUT_USER: ${{ secrets.LOCKED_OUT_USER }}
          PROBLEM_USER: ${{ secrets.PROBLEM_USER }}
          PERFORMANCE_USER: ${{ secrets.PERFORMANCE_USER }}
          ERROR_USER: ${{ secrets.ERROR_USER }}
          VISUAL_USER: ${{ secrets.VISUAL_USER }}
          COMMON_PASSWORD: ${{ secrets.COMMON_PASSWORD }}
